# Read the README file for more detailed configuration information
# https://github.com/gpslab/geoip2
gpslab_geoip:
    # You should specify your personal licence key
    license: '%env(MAXMIND_LICENSE_KEY)%'


    databases:
        asn:
            edition: 'GeoLite2-ASN'
            locales: [ 'de' ]
        country:
            edition: 'GeoLite2-Country'
            locales: [ 'de' ]
